In [75]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import sklearn.metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
#import xgboost

df = pd.read_csv("WorldCupMatches.csv")

np.random.seed(0)

In [87]:
df = pd.read_csv("results2.csv")
#print(df.columns)
isHome = lambda x:pd.Series(df["Home Team Name"] == x)
isAway = lambda x:pd.Series(df["Away Team Name"] == x)
isWin = lambda x:pd.Series(df["Home Win"] == x)
#isStage = lambda x:pd.Series(df["Stage"] == x )

Nation = "Morocco"
print(Nation)
print("Home Appearances = " + str(isHome(Nation).sum()))
print("Away Appearances = " + str(isAway(Nation).sum()))
print("Total Apperances = " + str(isHome(Nation).sum() + isAway(Nation).sum()))
#print("Win = " + str(isWin(Nation).sum()))
print("Win Percentage = {0:.1f}%".format(100*isWin(Nation).sum()/(isHome(Nation).sum() + isAway(Nation).sum())) )

#print((df["Win"] == "Germany").count())
#features[((features["Away Team Name"] == "Brazil") |(features["Home Team Name"] == "Brazil"))  & (features['Stage'] == "Final" )]

Morocco
Home Appearances = 201
Away Appearances = 156
Total Apperances = 357
Win Percentage = 65.3%


In [37]:
wc_teams = ['Australia','Iran','Japan','Korea','Saudi Arabia',
            'Egypt','Morocco','Nigeria','Senegal','Tunisia',
            'Costa Rica','Mexico','Panama','Argentina','Brazil',
            'Colombia','Peru','Uruguay','Belgium','Croatia','Denmark',
            'England','France','Germany','Iceland','Poland','Portugal',
            'Russia','Serbia','Spain','Sweden','Switzerland']
#df = (df[df.Year!=2018])
features = (df.drop(['date', 'tournament','city','country','neutral'],axis=1))

In [38]:
"""
isHome = lambda x:pd.Series(df["Home Team Name"] == x)
isAway = lambda x:pd.Series(df["Away Team Name"] == x)
isWin = lambda x:pd.Series(df["Win"] == x)
isStage = lambda x:pd.Series(df["Stage"] == x )

Nation = "Germany"

print("Home Appearances = " + str(isHome(Nation).sum()))
print("Away Appearances = " + str(isAway(Nation).sum()))
print("Total Apperances = " + str(isHome(Nation).sum() + isAway(Nation).sum()))
#print("Win = " + str(isWin(Nation).sum()))
print("Win Percentage = {0:.1f}%".format(100*isWin(Nation).sum()/(isHome(Nation).sum() + isAway(Nation).sum())) )

#print((df["Win"] == "Germany").count())
#features[((features["Away Team Name"] == "Brazil") |(features["Home Team Name"] == "Brazil"))  & (features['Stage'] == "Final" )]

SyntaxError: EOF while scanning triple-quoted string literal (<ipython-input-38-710ed7e10744>, line 16)

In [39]:
#print(df[(df["Stage"] == "Quarter-finals") & (df["Home Team Name"].str.contains(Nation) | df["Away Team Name"].str.contains(Nation))])
features['Home Win'] = features["Home Score"] > features["Away Score"]
#features['Home Team Name'] = features['Home Team Name'].replace('Germany FR', 'Germany')
#features['Away Team Name'] = features['Away Team Name'].replace('Germany FR', 'Germany')

wc_home = features[features['Home Team Name'].isin(wc_teams)]
wc_away = features[features['Away Team Name'].isin(wc_teams)]
final = pd.concat((wc_home,wc_away))

final = final.drop(['Home Score','Away Score'],axis=1)
final.drop_duplicates()
#features[(features['Home Team Name'] == "Italy") & (features['Stage'] == "Final")]
#one_hot = pd.get_dummies(features)
#print(final)
final["Home Win"] 

0         True
4        False
8         True
9         True
14       False
15       False
22        True
23        True
24       False
32        True
43        True
45        True
47       False
49        True
56        True
57        True
59       False
67        True
68        True
76        True
77        True
80        True
85        True
87        True
93        True
96        True
97       False
104       True
107       True
109       True
         ...  
30483     True
30484     True
30485    False
30486     True
30487    False
30488     True
30489     True
30490    False
30491     True
30492    False
30493     True
30494     True
30495    False
30496    False
30497     True
30498    False
30499    False
30500    False
30501     True
30502    False
30503    False
30504    False
30505    False
30506    False
30507    False
30508     True
30509     True
30510     True
30511     True
30512     True
Name: Home Win, Length: 15549, dtype: bool

In [40]:
encoded = pd.get_dummies(final)
print(encoded.columns)
labels = encoded['Home Win'].values

#encoded["is_train"]=np.random.uniform(0,1,len(encoded)) <= .7

#features.head(10)

features = encoded.loc[:, encoded.columns != "Home Win"]

Index(['Home Win', 'Home Team Name_Afghanistan', 'Home Team Name_Albania',
       'Home Team Name_Algeria', 'Home Team Name_Andorra',
       'Home Team Name_Angola', 'Home Team Name_Argentina',
       'Home Team Name_Armenia', 'Home Team Name_Australia',
       'Home Team Name_Austria',
       ...
       'Away Team Name_Vanuatu', 'Away Team Name_Venezuela',
       'Away Team Name_Vietnam', 'Away Team Name_Vietnam Republic',
       'Away Team Name_Wales', 'Away Team Name_Yemen',
       'Away Team Name_Yemen DPR', 'Away Team Name_Yugoslavia',
       'Away Team Name_Zambia', 'Away Team Name_Zimbabwe'],
      dtype='object', length=409)


In [41]:
labels

array([ True, False,  True, ...,  True,  True,  True])

In [42]:
#train,test = encoded[encoded['is_train'] == True],encoded[encoded['is_train'] == False]

train_features,test_features,train_labels,test_labels = train_test_split(features,labels,test_size = 0.25,random_state = 42)

print('Number of Features in the training data:', train_features.shape)
print('Number of Labels in the training data:', train_labels.shape)
print('Number of Features in the test data:', test_features.shape)
print('Number of Labels in the test data:',test_labels.shape)

Number of Features in the training data: (11661, 408)
Number of Labels in the training data: (11661,)
Number of Features in the test data: (3888, 408)
Number of Labels in the test data: (3888,)


In [334]:
#encoded = encoded.drop(['Home Win', 'is_train'])
#labels = list(labels).pop()
#home_win = train['Home Win'].values

In [335]:
#train[labels]

In [43]:
#print(train[labels])

NameError: name 'train' is not defined

In [77]:
#clf = RandomForestClassifier(n_jobs=-1, random_state = 3, min_samples_split = 2)
#clf = DecisionTreeClassifier(max_depth = 100)
clf = LogisticRegression()
#clf = DecisionTreeClassifier(max_depth = 100)
clf.fit(train_features,train_labels)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [78]:
predictions = clf.predict(test_features)
#errors = abs(predictions - test_labels)
#eval_model = test[["Home Win","Predict"]]
from sklearn.metrics import accuracy_score
#print("Train Score: " + str(accuracy_score(pred,train["Home Win"].values)))
print("Test Score: " + str(accuracy_score(test_labels,predictions)*100))
#accuracy_score(test["Home Win"],test["Predict"])

Test Score: 73.19958847736625


In [79]:
sklearn.metrics.confusion_matrix(test_labels,predictions)

array([[ 745,  719],
       [ 323, 2101]], dtype=int64)

In [80]:
(np.sum(eval_model["Home Win"] == eval_model["Predict"]))/(eval_model.count())

NameError: name 'eval_model' is not defined

In [373]:
#print(test[labels])

In [48]:
wc_teams = ['Australia','Iran','Japan','Korea','Saudi Arabia',
            'Egypt','Morocco','Nigeria','Senegal','Tunisia',
            'Costa Rica','Mexico','Panama','Argentina','Brazil',
            'Colombia','Peru','Uruguay','Belgium','Croatia','Denmark',
            'England','France','Germany','Iceland','Poland','Portugal',
            'Russia','Serbia','Spain','Sweden','Switzerland']
wc_home = features[features['Home Team Name'].isin(wc_teams)]
wc_home = wc_home.drop(columns='Stage')
wc_away = features[features['Away Team Name'].isin(wc_teams)]
wc_away = wc_away.drop(columns='Stage')
wc_teams = pd.concat((wc_home,wc_away))
wc_teams.drop_duplicates()
wc_teams.count()
wc_teams
final_pred = pd.get_dummies(wc_teams)
final_pred = final_pred.drop(["Home Team Goals","Away Team Goals","Home Team Win"],axis = 1)

KeyError: 'Home Team Name'

In [82]:
group = {"Home Team Name" : ["Russia","Egypt","Russia","Uruguay","Uruguay","Saudi Arabia","Morocco","Portugal","Portugal","Iran","Spain","Iran","France","Peru","Denmark","France","Australia","Denmark","Argentina","Croatia","Argentina","Nigeria","Nigeria","Iceland","Costa Rica","Brazil","Brazil","Serbia","Serbia","Switzerland","Germany","Sweden","Korea Republic","Germany","Korea Republic","Mexico","Belgium","Tunisia","Belgium","England","Panama","England","Colombia","Poland","Japan","Poland","Japan","Senegal"],
           "Away Team Name" : ["Saudi Arabia", "Uruguay","Egypt","Saudi Arabia","Russia","Egypt","Iran","Spain","Morocco","Spain","Morocco","Portugal","Australia","Denmark","Australia","Peru","Peru","France","Iceland","Nigeria","Croatia","Iceland","Argentina","Croatia","Serbia","Switzerland","Costa Rica","Switzerland","Brazil","Costa Rica","Mexico","Korea Republic","Mexico","Sweden","Germany","Sweden","Panama","England","Tunisia","Panama","Tunisia","Belgium","Japan","Senegal","Senegal","Colombia","Poland","Colombia"]}
WC = pd.DataFrame.from_dict(group)
#WC["Home Team Name"] = "Russia"
#WC["Away Team Name"] = "Saudi Arabia"
predict_set = pd.get_dummies(WC)
WC_col = features.iloc[:0]
WC_col = WC_col.append(predict_set)
WC_col.fillna(value = 0,inplace = True)
#predict_set
#set(WC_col.columns) - set(features.columns)
predictions = clf.predict(WC_col)
for i in predictions:
    print(i)

True
True
False
True
True
True
True
True
True
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
False
True
False
False
False
False
False
False
True
True


In [85]:
elimination = {"Home Team Name" : ["Egypt","Uruguay","France","Denmark","Brazil","Switzerland","Tunisia","Belgium"],
           "Away Team Name" : ["Portugal","Morocco","Nigeria","Argentina","Korea Republic","Germany","Colombia","Senegal"]}
WC = pd.DataFrame.from_dict(elimination)
#WC["Home Team Name"] = "Russia"
#WC["Away Team Name"] = "Saudi Arabia"
predict_set = pd.get_dummies(WC)
WC_col = features.iloc[:0]
WC_col = WC_col.append(predict_set)
WC_col.fillna(value = 0,inplace = True)
#predict_set
#set(WC_col.columns) - set(features.columns)
predictions = clf.predict(WC_col)
for i in predictions:
    print(i)

True
False
True
True
True
True
True
False


In [88]:
quarter = {"Home Team Name" : ["Egypt","Morocco","Brazil","Switzerland"],
           "Away Team Name" : ["France","Denmark","Tunisia","Senegal"]}
WC = pd.DataFrame.from_dict(quarter)
#WC["Home Team Name"] = "Russia"
#WC["Away Team Name"] = "Saudi Arabia"
predict_set = pd.get_dummies(WC)
WC_col = features.iloc[:0]
WC_col = WC_col.append(predict_set)
WC_col.fillna(value = 0,inplace = True)
#predict_set
#set(WC_col.columns) - set(features.columns)
predictions = clf.predict(WC_col)
for i in predictions:
    print(i)

True
True
False
True


In [72]:
semi = {"Home Team Name" : ["Morocco","Sweden"],
           "Away Team Name" : ["Argentina","Senegal"]}
WC = pd.DataFrame.from_dict(semi)
#WC["Home Team Name"] = "Russia"
#WC["Away Team Name"] = "Saudi Arabia"
predict_set = pd.get_dummies(WC)
WC_col = features.iloc[:0]
WC_col = WC_col.append(predict_set)
WC_col.fillna(value = 0,inplace = True)
#predict_set
#set(WC_col.columns) - set(features.columns)
predictions = clf.predict_proba(WC_col)
print(predictions)

[[0.68484848 0.31515152]
 [0.35       0.65      ]]


In [73]:
final = {"Home Team Name" : ["Argentina"],
           "Away Team Name" : ["Sweden"]}
WC = pd.DataFrame.from_dict(final)
#WC["Home Team Name"] = "Russia"
#WC["Away Team Name"] = "Saudi Arabia"
predict_set = pd.get_dummies(WC)
WC_col = features.iloc[:0]
WC_col = WC_col.append(predict_set)
WC_col.fillna(value = 0,inplace = True)
#predict_set
#set(WC_col.columns) - set(features.columns)
predictions = clf.predict_proba(WC_col)
print(predictions)

[[0.65166667 0.34833333]]
